-- Supabase DDL for thispagedoesnotexist12345.me Boarding Flow
--
-- This migration sets up the `passengers` table, a sequence for unique IDs,
-- an RPC to mint new IDs, and a unique index for idempotency.

-- 1. Create the main `passengers` table
CREATE TABLE IF NOT EXISTS public.passengers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone,

  -- Core passenger identifiers
  passenger_id text not null unique,
  email text not null,
  flight_tag text not null,

  -- Form data
  name text,
  passenger_type text,
  broken_tooling text,
  desired_gap text,
  notes text,
  beta_ack boolean default false,

  -- Metadata
  status text default 'Invited',
  source text
);

-- 2. Create sequence for minting passenger IDs
CREATE SEQUENCE IF NOT EXISTS public.passenger_seq START 1;

-- 3. Create RPC to get the next formatted passenger ID (e.g., PX-000001)
CREATE OR REPLACE FUNCTION public.get_next_passenger_id()
RETURNS text
LANGUAGE sql
AS $$
  SELECT 'PX-' || lpad(nextval('public.passenger_seq')::text, 6, '0');
$$;

-- 4. Add unique index for idempotency on (email, flight_tag)
-- This prevents duplicate entries for the same person on the same flight.
CREATE UNIQUE INDEX IF NOT EXISTS passengers_email_flight_tag_unique
ON public.passengers (lower(email), flight_tag);

-- Grant usage to the anon and authenticated roles so the function can be called
GRANT USAGE ON SEQUENCE public.passenger_seq TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_next_passenger_id() TO anon, authenticated;
